/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardInvitationsRouteImport } from './routes/_dashboard/invitations'
import { Route as DashboardLedgersIndexRouteImport } from './routes/_dashboard/ledgers/index'
import { Route as DashboardLedgersLedgerIdRouteRouteImport } from './routes/_dashboard/ledgers/$ledgerId/route'
import { Route as DashboardLedgersLedgerIdIndexRouteImport } from './routes/_dashboard/ledgers/$ledgerId/index'
import { Route as DashboardLedgersLedgerIdMembersRouteImport } from './routes/_dashboard/ledgers/$ledgerId/members'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLedgersIndexRoute = DashboardLedgersIndexRouteImport.update({
  id: '/ledgers/',
  path: '/ledgers/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLedgersLedgerIdRouteRoute =
  DashboardLedgersLedgerIdRouteRouteImport.update({
    id: '/ledgers/$ledgerId',
    path: '/ledgers/$ledgerId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLedgersLedgerIdIndexRoute =
  DashboardLedgersLedgerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLedgersLedgerIdRouteRoute,
  } as any)
const DashboardLedgersLedgerIdMembersRoute =
  DashboardLedgersLedgerIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => DashboardLedgersLedgerIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/invitations': typeof DashboardInvitationsRoute
  '/ledgers/$ledgerId': typeof DashboardLedgersLedgerIdRouteRouteWithChildren
  '/ledgers/': typeof DashboardLedgersIndexRoute
  '/ledgers/$ledgerId/members': typeof DashboardLedgersLedgerIdMembersRoute
  '/ledgers/$ledgerId/': typeof DashboardLedgersLedgerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/invitations': typeof DashboardInvitationsRoute
  '/ledgers': typeof DashboardLedgersIndexRoute
  '/ledgers/$ledgerId/members': typeof DashboardLedgersLedgerIdMembersRoute
  '/ledgers/$ledgerId': typeof DashboardLedgersLedgerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_dashboard/invitations': typeof DashboardInvitationsRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/ledgers/$ledgerId': typeof DashboardLedgersLedgerIdRouteRouteWithChildren
  '/_dashboard/ledgers/': typeof DashboardLedgersIndexRoute
  '/_dashboard/ledgers/$ledgerId/members': typeof DashboardLedgersLedgerIdMembersRoute
  '/_dashboard/ledgers/$ledgerId/': typeof DashboardLedgersLedgerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/invitations'
    | '/ledgers/$ledgerId'
    | '/ledgers/'
    | '/ledgers/$ledgerId/members'
    | '/ledgers/$ledgerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/invitations'
    | '/ledgers'
    | '/ledgers/$ledgerId/members'
    | '/ledgers/$ledgerId'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_dashboard/invitations'
    | '/_dashboard/'
    | '/_dashboard/ledgers/$ledgerId'
    | '/_dashboard/ledgers/'
    | '/_dashboard/ledgers/$ledgerId/members'
    | '/_dashboard/ledgers/$ledgerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/invitations': {
      id: '/_dashboard/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/ledgers/': {
      id: '/_dashboard/ledgers/'
      path: '/ledgers'
      fullPath: '/ledgers/'
      preLoaderRoute: typeof DashboardLedgersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/ledgers/$ledgerId': {
      id: '/_dashboard/ledgers/$ledgerId'
      path: '/ledgers/$ledgerId'
      fullPath: '/ledgers/$ledgerId'
      preLoaderRoute: typeof DashboardLedgersLedgerIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/ledgers/$ledgerId/': {
      id: '/_dashboard/ledgers/$ledgerId/'
      path: '/'
      fullPath: '/ledgers/$ledgerId/'
      preLoaderRoute: typeof DashboardLedgersLedgerIdIndexRouteImport
      parentRoute: typeof DashboardLedgersLedgerIdRouteRoute
    }
    '/_dashboard/ledgers/$ledgerId/members': {
      id: '/_dashboard/ledgers/$ledgerId/members'
      path: '/members'
      fullPath: '/ledgers/$ledgerId/members'
      preLoaderRoute: typeof DashboardLedgersLedgerIdMembersRouteImport
      parentRoute: typeof DashboardLedgersLedgerIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardLedgersLedgerIdRouteRouteChildren {
  DashboardLedgersLedgerIdMembersRoute: typeof DashboardLedgersLedgerIdMembersRoute
  DashboardLedgersLedgerIdIndexRoute: typeof DashboardLedgersLedgerIdIndexRoute
}

const DashboardLedgersLedgerIdRouteRouteChildren: DashboardLedgersLedgerIdRouteRouteChildren =
  {
    DashboardLedgersLedgerIdMembersRoute: DashboardLedgersLedgerIdMembersRoute,
    DashboardLedgersLedgerIdIndexRoute: DashboardLedgersLedgerIdIndexRoute,
  }

const DashboardLedgersLedgerIdRouteRouteWithChildren =
  DashboardLedgersLedgerIdRouteRoute._addFileChildren(
    DashboardLedgersLedgerIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLedgersLedgerIdRouteRoute: typeof DashboardLedgersLedgerIdRouteRouteWithChildren
  DashboardLedgersIndexRoute: typeof DashboardLedgersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLedgersLedgerIdRouteRoute:
    DashboardLedgersLedgerIdRouteRouteWithChildren,
  DashboardLedgersIndexRoute: DashboardLedgersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
