/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as DashboardLayoutIndexRouteImport } from './routes/_dashboardLayout/index'
import { Route as DashboardLayoutEntriesRouteImport } from './routes/_dashboardLayout/entries'
import { Route as AuthLayoutLoginRouteImport } from './routes/_authLayout/login'

const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)
const DashboardLayoutEntriesRoute = DashboardLayoutEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => DashboardLayoutRouteRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardLayoutIndexRoute
  '/login': typeof AuthLayoutLoginRoute
  '/entries': typeof DashboardLayoutEntriesRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardLayoutIndexRoute
  '/login': typeof AuthLayoutLoginRoute
  '/entries': typeof DashboardLayoutEntriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_dashboardLayout/entries': typeof DashboardLayoutEntriesRoute
  '/_dashboardLayout/': typeof DashboardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/entries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/entries'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_dashboardLayout'
    | '/_authLayout/login'
    | '/_dashboardLayout/entries'
    | '/_dashboardLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/': {
      id: '/_dashboardLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/entries': {
      id: '/_dashboardLayout/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof DashboardLayoutEntriesRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutEntriesRoute: typeof DashboardLayoutEntriesRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutEntriesRoute: DashboardLayoutEntriesRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
